### ISSUE TITLE
`GPU Updater Tool.ps1` throws exception "Value cannot be null. Parameter name: address"

### ISSUE THREAD

**Issue by ghost** [jamesstringerparsec/Cloud-GPU-Updater#1]
https://github.com/jamesstringerparsec/Cloud-GPU-Updater/blob/6e3f42c526eb413854fba8f2ce59e2d50ce41102/GPU%20Updater%20Tool.ps1#L208-L218

#### Configuration

- **OS**: Windows Server 2016 Datacenter
- **Tier**: Standard NV6

#### To reproduce

1. **Manually** deploy a new Virtual Machine from [Azure Portal](https://portal.azure.com) with the configurations below:
```
Location: South Central US
Virtual Machine Size: Standard NV6
Allow Public Inbound Port: RDP:3389
Data Disks: Standard SSD 1023 GiB (Attached)
```

2. After deployment successfully created, connect to the virtual machine through **Microsoft Remote Desktop**
3. Copy the **script** referenced [here](https://github.com/jamesstringerparsec/Parsec-Cloud-Preparation-Tool/blob/master/Readme.md#user-content-instructions) and paste into PowerShell (Admin)
4. After the PowerShell window closed automatically. Run `PostInstall.ps1`, it will install Chrome, Parsec, etc... Follow the steps in the output of PowerShell window.
5. Run `GPU Updater.Ink` which is located at **Desktop**.

**If It's about the script, It will produce same error. If not**:

#### What I've done to fix it

- _Windows Firewall_ was **On**. Turned off and tried again. Gave the same error.
- Tried to run the `GPU Updater Tool.ps1` in **PowerShell ISE**

**Comment by jamesstringer90** [comment]
As I asked in the Discord, please provide the output of this code block on your NV6 machine.

function installedGPUID {
#queries WMI to get DeviceID of the installed NVIDIA GPU
Try {(get-wmiobject -query "select DeviceID from Win32_PNPEntity Where (deviceid Like '%PCI\\VEN_10DE%') and (PNPClass = 'Display' or Name = '3D Video Controller')"  | Select-Object DeviceID -ExpandProperty DeviceID).substring(13,8)}

Catch {return $null}
}

installedgpuid

**Comment by jamesstringer90** [comment]
I had no follow up from submitter and wasn't able to replicate the issue myself.
Closing this.
