### ISSUE TITLE
GPU update tool doesn't correctly recognize Azure

### ISSUE THREAD

**Issue by anaisbetts** [jamesstringerparsec/Cloud-GPU-Updater#2]
GPU Update tool seems to [ping an internal network endpoint](https://github.com/jamesstringerparsec/Cloud-GPU-Updater/blob/master/GPU%20Updater%20Tool.ps1#L55) for Azure that now has issues with TLS (or possibly just flat-out doesn't work) - when I edited the script and hardcoded the result to Azure it all worked

**Comment by jamesstringer90** [comment]
Yeap, it tries to see if the machine is Azure by checking the format of the metadata.  Looks like maybe they changed something on their end, I'll see if I can find a more reliable way of confirming its an Azure machine.

**Comment by jamesstringer90** [comment]
This issue is resolved, 

added to begining of script to set invoke-webrequest to use TLS 1.2

```[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12```
