### ISSUE TITLE
Update tool does not work on AWS g2.2xlarge instances

### ISSUE THREAD

**Issue by NitriKx** [jamesstringerparsec/Cloud-GPU-Updater#3]
After trying this tool on the AWS g2.2xlarge instances, I found out that the downloaded driver is not compatible with Windows Server 2016.

The downloaded driver for GRID K520 is https://ec2-windows-nvidia-drivers.s3.amazonaws.com/latest/431.02_grid_win10_server2016_server2019_64bit_international.exe but this one does not work with server2016 + K520.

The official website shows that the latest driver for this card is 370.39 (grid-4.6) (https://www.nvidia.com/download/driverResults.aspx/151636/en-us). That is probably why [AWS Documentation](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/install-nvidia-driver-windows.html#nvidia-drivers-public) says that the drivers should be downloaded manually and not from the S3 bucket.

**Comment by jamesstringer90** [comment]
Hmmmmm, that shouldn't be happening.  It should download the 370.39 driver.   I'll check it out.

**Comment by jamesstringer90** [comment]
This has been resolved in the following commit 

https://github.com/jamesstringerparsec/Cloud-GPU-Updater/commit/162ca16f0fa8963bd09267c8fd1ab55e8f1d82fb#diff-d3c4aadd07257c384d13d4482fefd5d6
