### ISSUE TITLE
GPU Updater crashes on AWS G4.xlarge, due to Nvidia driver directory structure changing

### ISSUE THREAD

**Issue by Shakahs** [jamesstringerparsec/Cloud-GPU-Updater#5]
The GPU updater crashes with the following error:

```
Move-Item : Cannot find path 'C:\ParsecTemp\Drivers\ExtractedGPUDriver\NVIDIA_445.87.exe' because it does not exist.
At C:\Users\Administrator\Documents\Untitled1.ps1:264 char:1
+ Move-Item -Path "$($system.Path)\ExtractedGPUDriver\NVIDIA_$($gpu.web ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\ParsecTemp\D...IDIA_445.87.exe:String) [Move-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand

```
This occurs because the ExtractedGPUDriver path needs to be changed to` "$($system.Path)\ExtractedGPUDriver\Windows"` as the directory structure of the driver ZIP file has changed:

```
Old:
├── 440.68-442.59-March2020-grid-vgaming-applicaton-note.pdf
├── 442.59_grid_vgaming_win10_64bit_international_whql.exe
├── 442.59_grid_vgaming_win8_win7_64bit_international_whql.exe
└── GRID-442.59-Mar2020-vGaming-Windows-Guest-Drivers.zip


New:
.
├── GRID-445.87-Apr2020-vGaming-Windows-Guest-Drivers.zip
└── Windows
    ├── 445.87-445.48-April2020-grid-vgaming-applicaton-note..pdf
    ├── 445.87_grid_vgaming_win10_64bit_international_whql.exe
    └── 445.87_grid_vgaming_win8_win7_64bit_international_whql.exe
```

https://github.com/jamesstringerparsec/Cloud-GPU-Updater/blob/e6832db7c9c74e62458121d8eb8bddb2f9047648/GPU%20Updater%20Tool.ps1#L262

Updating the path on that line and the next few resolved the issue on my instance. Thank you for this tool.

**Comment by jamesstringer90** [comment]
Hey, I just fixed this :)

Great bug report by the way.

**Comment by amcolex** [comment]
@jamesstringerparsec Hi James.

I'd like to re-open this issue, as it seems that NVidia has changed the directory structure yet again. 

Switching it back to `"$($system.Path)\ExtractedGPUDriver\"` seems to solve the issue.
