### ISSUE TITLE
Incorrect console output when upgrading driver

### ISSUE THREAD

**Issue by Shakahs** [jamesstringerparsec/Cloud-GPU-Updater#6]
https://github.com/jamesstringerparsec/Cloud-GPU-Updater/blob/37c27c66ba511bd9ff6d8229144e17c61bf0a694/GPU%20Updater%20Tool.ps1#L146

When upgrading a driver I get this output saying version 442 is greater than version 445. The script does the right thing, it just outputs an incorrect string:

`Checked Now 04/22/2020 22:03:28 - An update is available (442.59 > 445.87)`

**Comment by jamesstringer90** [comment]
It's saying it's going from 442.59 -> 445.87 not that 442.59 is greater than 445.87.
