### ISSUE TITLE
Support Windows Server 2012 R2 [atleast for Azure]

### ISSUE THREAD

**Issue by SoftwareRat** [jamesstringerparsec/Cloud-GPU-Updater#7]
Hello,
many people like to use Windows Server 2012 R2 for Cloud Gaming usage because not everyone is a friend of Windows 10.
So unlike Windows 8.1, I see reasons to support Server 2012.

Would be nice if you support it, I can even help you if you want.

On AWS and Google Cloud, I am not sure if they support GRID drivers for Server 2012, but on Azure they support

**Comment by jamesstringer90** [comment]
There are no plans to add support for 2012 R2
