### ISSUE TITLE
GPU udpater error on AWS g4dn.xlarge instance

### ISSUE THREAD

**Issue by fabioclordelo** [jamesstringerparsec/Cloud-GPU-Updater#9]
I'm getting the following error when trying to run the script:

PS C:\Users\Administrator\Downloads\Cloud-GPU-Updater-master\Cloud-GPU-Updater-master> C:\Users\Administrator\Downloads\Cloud-GPU-Updater-master\Cloud-GPU-Updater-master\GPUUpdaterTool.ps1
At C:\Users\Administrator\Downloads\Cloud-GPU-Updater-master\Cloud-GPU-Updater-master\GPUUpdaterTool.ps1:443 char:65
+ ... e_ID -eq "DEV_1EB8â€ ) -or $($gpu.Device_ID -eq "DEV_15F8â€ ) -or $($ ...
+                                                     ~~~~~~~~~~~~~
The string is missing the terminator: ".
At C:\Users\Administrator\Downloads\Cloud-GPU-Updater-master\Cloud-GPU-Updater-master\GPUUpdaterTool.ps1:443 char:79
+ ... _ID -eq "DEV_1EB8â€ ) -or $($gpu.Device_ID -eq "DEV_15F8â€ ) -or $($g ...
+                                                                  ~
Missing closing ')' in subexpression.
At C:\Users\Administrator\Downloads\Cloud-GPU-Updater-master\Cloud-GPU-Updater-master\GPUUpdaterTool.ps1:443 char:104
+ ... e_ID -eq "DEV_15F8â€ ) -or $($gpu.Device_ID -eq "DEV_1BB3â€ ) -or $($ ...
+                                                     ~~~~~~~~~~~~~
The string is missing the terminator: ".
At C:\Users\Administrator\Downloads\Cloud-GPU-Updater-master\Cloud-GPU-Updater-master\GPUUpdaterTool.ps1:443 char:118
+ ... _ID -eq "DEV_15F8â€ ) -or $($gpu.Device_ID -eq "DEV_1BB3â€ ) -or $($g ...
+                                                                  ~
Missing closing ')' in subexpression.
At C:\Users\Administrator\Downloads\Cloud-GPU-Updater-master\Cloud-GPU-Updater-master\GPUUpdaterTool.ps1:443 char:143
+ ... Device_ID -eq "DEV_1BB3â€ ) -or $($gpu.Device_ID -eq "DEV_7362â€ )) {
+                                                          ~~~~~~~~~~~~~
The string is missing the terminator: ".
At C:\Users\Administrator\Downloads\Cloud-GPU-Updater-master\Cloud-GPU-Updater-master\GPUUpdaterTool.ps1:443 char:157
+ ... Device_ID -eq "DEV_1BB3â€ ) -or $($gpu.Device_ID -eq "DEV_7362â€ )) {
+                                                                        ~
Missing closing ')' in subexpression.
At C:\Users\Administrator\Downloads\Cloud-GPU-Updater-master\Cloud-GPU-Updater-master\GPUUpdaterTool.ps1:456 char:30
+ ... ported -eq "UnOfficial") -and ($gpu.cloudprovider -eq "aws") -and ($g ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'UnOfficial") -and ($gpu.cloudprovider -eq "aws") -and ($gpu.Device_ID -eq "DEV_1EB8")) -eq $true){
        $S3Path = AWSPrivatedriver -profileName ParsecGPUUpdate -GPU "G4dn"
        (New-Object System.Net.WebClient).DownloadFile($("https://nvidia-gaming.s3.amazonaws.com/" + $s3path), $($system.Path) + "\NVIDIA_" 
+ $($gpu.web_driver) + ".zip")
        Expand-Archive -Path ($($system.Path) + "\NVIDIA_" + $($gpu.web_driver) + ".zip") -DestinationPath 
"$($system.Path)\ExtractedGPUDriver\"
        $extractedpath = Get-ChildItem -Path "$($system.Path)\ExtractedGPUDriver\Windows\" | Where-Object name -like '*win10*' | % name
        Rename-Item -Path "$($system.Path)\ExtractedGPUDriver\Windows\$extractedpath" -NewName "NVIDIA_$($gpu.web_driver).exe"
        Move-Item -Path "$($system.Path)\ExtractedGPUDriver\Windows\NVIDIA_$($gpu.web_driver).exe" -Destination $system.Path
        remove-item "$($system.Path)\NVIDIA_$($gpu.web_driver).zip"
        remove-item "$($system.Path)\ExtractedGPUDriver" -Recurse
        (New-Object 
System.Net.WebClient).DownloadFile("https://nvidia-gaming.s3.amazonaws.com/GridSwCert-Archive/GridSwCert-Windows_2020_04.cert", 
"C:\Users\Public\Documents\GridSwCert.txt")
        ClearG4DNCredentials ParsecGPUUpdate
    }
    Elseif((($gpu.Supported -eq "UnOfficial") -and ($gpu.cloudprovider -eq "aws") -and ($gpu.Device_ID -eq "DEV_7362")) -eq $true){
        $S3Path = AWSPrivatedriver -profileName ParsecGPUUpdate -GPU "G4ad"
        (New-Object System.Net.WebClient).DownloadFile($("https://ec2-amd-windows-drivers.s3.amazonaws.com/" + $s3path), $($system.Path) + 
"\AMD_" + $($gpu.web_driver) + ".zip")
        Expand-Archive -Path ($($system.Path) + "\AMD_" + $($gpu.web_driver) + ".zip") -DestinationPath "$($system.Path)\ExtractedGPUDriver\"
        $GPU.AMDExtractedPath = Get-ChildItem -Path "$($system.Path)\ExtractedGPUDriver\" -recurse -Directory | Where-Object name -like 
'*WT6A_INF*' | % FullName
    }
    Elseif ((($gpu.supported -eq "UnOfficial")  -and ($gpu.cloudprovider -eq "Google"))-eq $true) {
        $googlestoragedriver =([xml](invoke-webrequest -uri 
https://storage.googleapis.com/nvidia-drivers-us-public).content).listbucketresult.contents.key  -like  "*GRID1*server2016*.exe" | select 
-last 1
        (New-Object System.Net.WebClient).DownloadFile($("https://storage.googleapis.com/nvidia-drivers-us-public/" + $googlestoragedriver), 
"C:\ParsecTemp\Drivers\GoogleGRID.exe")
        }
    Elseif((($gpu.Supported -eq "yes") -and ($gpu.cloudprovider -eq "aws") -and ($gpu.Device_ID -ne "DEV_118A") -and ($gpu.Device_ID -ne 
"DEV_1EB8")) -eq $true) {
        $s3path = $(([xml](invoke-webrequest -uri 
https://ec2-windows-nvidia-drivers.s3.amazonaws.com).content).listbucketresult.contents.key -like  "latest/*server2016*") 
        (New-Object System.Net.WebClient).DownloadFile($("https://ec2-windows-nvidia-drivers.s3.amazonaws.com/" + $s3path), $($system.Path) 
+ "\NVIDIA_" + $($gpu.web_driver) + ".exe")
        }
    Elseif((($gpu.Supported -eq "yes") -and ($gpu.cloudprovider -eq "azure")) -eq $true){
        $azuresupportpage = (Invoke-WebRequest -Uri https://docs.microsoft.com/en-us/azure/virtual-machines/windows/n-series-driver-setup 
-UseBasicParsing).links.outerhtml -like "*GRID*"
        (New-Object System.Net.WebClient).DownloadFile($($azuresupportpage[0].split('"')[1]), $($system.Path) + "\NVIDIA_" + 
$($gpu.web_driver) + ".exe")
        }
    Else {
        #downloads driver from nvidia.com
        $Download.Link = Invoke-WebRequest -Uri $gpu.url -Method Get -UseBasicParsing | select @{N='Latest';E={$($_.links.href 
-match"www.nvidia.com/download/driverResults.aspx*")[0].substring(2)}}
        $download.Direct = Invoke-WebRequest -Uri $download.link.latest -Method Get -UseBasicParsing | select @{N= 'Download'; 
E={"http://us.download.nvidia.com" + $($_.links.href -match "/content/driverdownload*").split('=')[1].split('&')[0]}}
        (New-Object System.Net.WebClient).DownloadFile($($download.direct.download), $($system.Path) + "\NVIDIA_" + $($gpu.web_driver) + 
".exe")
        }
}
function Test-RegistryValue {
    # https://www.jonathanmedd.net/2014/02/testing-for-the-presence-of-a-registry-key-and-value.html
    param (
     [parameter(Mandatory=$true)]
     [ValidateNotNullOrEmpty()]$Path,
    [parameter(Mandatory=$true)]
     [ValidateNotNullOrEmpty()]$Value
    )
    try {
        Get-ItemProperty -Path $Path | Select-Object -ExpandProperty $Value -ErrorAction Stop | Out-Null
        return $true
        }
    catch {
        return $false
        }
}
function DisableSecondMonitor {
    #downloads script to set GPU to WDDM if required
    (New-Object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/parsec-cloud/Cloud-GPU-Updater/master/Additional%20File
s/DisableSecondMonitor.ps1", $($system.Path) + "\DisableSecondMonitor.ps1") 
    Unblock-File -Path "$($system.Path)\DisableSecondMonitor.ps1"
}
function DisableSecondMonitor-shortcut{
    #creates startup shortcut that will start the script downloaded in setnvsmi
    #Write-Output "Generic' in expression or statement.
At C:\Users\Administrator\Downloads\Cloud-GPU-Updater-master\Cloud-GPU-Updater-master\GPUUpdaterTool.ps1:572 char:28
+                    ((//////
+                            ~
Missing closing ')' in expression.
At C:\Users\Administrator\Downloads\Cloud-GPU-Updater-master\Cloud-GPU-Updater-master\GPUUpdaterTool.ps1:587 char:27
+                          *#############///
+                           ~
You must provide a value expression following the '*' operator.
At C:\Users\Administrator\Downloads\Cloud-GPU-Updater-master\Cloud-GPU-Updater-master\GPUUpdaterTool.ps1:591 char:19
+                   ~Parsec GPU Updater~
+                   ~~~~~~~
Unexpected token '~Parsec' in expression or statement.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
 

PS C:\Users\Administrator\Downloads\Cloud-GPU-Updater-master\Cloud-GPU-Updater-master>

**Comment by jamesstringer90** [comment]
Download the script again and try, I fixed it.
